FROM maven:3.9-eclipse-temurin-21

WORKDIR /app

COPY settings.xml ./settings.xml
COPY pom.xml ./

# 启动 Spring Boot，注入远程 Debug 的 JAVA_OPTS 参数
CMD mvn -s ./settings.xml spring-boot:run "-Dspring-boot.run.jvmArguments=${JAVA_OPTS}"
