spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      timeout: 3s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expire-seconds: ${JWT_EXPIRE_SECONDS:7200}
